### ISSUE TITLE
muk_mail_branding / web_utils errors

### ISSUE THREAD

**Issue by admin-logfy** [muk-it/muk_misc#11]
Hello guys, I wanted to try out your mail branding app, so I installed it and all dependencies mentioned [here ](https://apps.odoo.com/apps/modules/12.0/muk_mail_branding/). I am running on Community v12.

Once installed The moment I've gone to /setting/General settings I got the following error:

**Error:
Uncaught Error: QWeb2: Template 'muk_web_utils.FieldColor' not found**

https://logfy.com.br/web/content/2558-b82900b/web.assets_common.js:3374
Traceback:
Error: QWeb2: Template 'muk_web_utils.FieldColor' not found
    at Object.exception (https://logfy.com.br/web/content/2558-b82900b/web.assets_common.js:3374:7)
    at Engine._render (https://logfy.com.br/web/content/2558-b82900b/web.assets_common.js:3419:103)
    at Engine.render (https://logfy.com.br/web/content/2558-b82900b/web.assets_common.js:3415:151)
    at Class.renderElement (https://logfy.com.br/web/content/2558-b82900b/web.assets_common.js:3673:1014)
    at Array.<anonymous> (https://logfy.com.br/web/content/2558-b82900b/web.assets_common.js:3683:6)
    at Array.<anonymous> (https://logfy.com.br/web/content/2558-b82900b/web.assets_common.js:802:681)
    at fire (https://logfy.com.br/web/content/2558-b82900b/web.assets_common.js:796:299)
    at Object.add [as done] (https://logfy.com.br/web/content/2558-b82900b/web.assets_common.js:797:467)
    at Array.<anonymous> (https://logfy.com.br/web/content/2558-b82900b/web.assets_common.js:802:649)
    at Function.each (https://logfy.com.br/web/content/2558-b82900b/web.assets_common.js:625:767

However, if I switch to Debug mode no error happened (which I found later in the process). **Any hints what is the solution for that?**

Lastly, as I urgently needed to continue our website customization, and needed access to General Settings, I've tried to uninstall the modules. Now I had another error, and I cannot uninstall the modules using the usual Apps/uninstall path. I've tried uninstall via "muk_utils", once all modules are to be removed...got the following error:

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo12/odoo12-server/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo12/odoo12-server/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo12/odoo12-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo12/odoo12-server/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/odoo12/odoo12-server/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo12/odoo12-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo12/odoo12-server/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo12/odoo12-server/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/odoo12/odoo12-server/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/odoo12/odoo12-server/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo12/odoo12-server/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo12/odoo12-server/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/odoo12/odoo12-server/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo12/odoo12-server/odoo/addons/base/wizard/base_module_uninstall.py", line 60, in action_uninstall
    return modules.button_immediate_uninstall()
  File "</usr/local/lib/python3.6/dist-packages/decorator.py:decorator-gen-64>", line 2, in button_immediate_uninstall
  File "/odoo12/odoo12-server/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo12/odoo12-server/odoo/addons/base/models/ir_module.py", line 586, in button_immediate_uninstall
    return self._button_immediate_function(type(self).button_uninstall)
  File "/odoo12/odoo12-server/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo12/odoo12-server/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo12/odoo12-server/odoo/modules/loading.py", line 473, in load_modules
    getattr(py_module, uninstall_hook)(cr, registry)
  File "<string>", line 61, in _uninstall_rebrand_system
  File "/usr/lib/python3.6/ast.py", line 85, in literal_eval
    return _convert(node_or_string)
  File "/usr/lib/python3.6/ast.py", line 61, in _convert
    return list(map(_convert, node.elts))
  File "/usr/lib/python3.6/ast.py", line 59, in _convert
    return tuple(map(_convert, node.elts))
  File "/usr/lib/python3.6/ast.py", line 84, in _convert
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: <_ast.Call object at 0x7f5110cc8828>

Please your valuable and urgent support is highly appreciated.

PS: no other app or setting was installed or changed after installing MuK modules.

**Comment by keshrath** [comment]
Update the modules and restart the server. Check if Odoo hast access rights to all the addon folders.

**Comment by admin-logfy** [comment]
Thanks @keshrath , issue solved!
