### ISSUE TITLE
Mail Branding > Uninstall

### ISSUE THREAD

**Issue by gregory-moka** [muk-it/muk_misc#4]
Issue when trying to uninstall the app : 

```
Erreur:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/OCB/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/OCB/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/OCB/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/OCB/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/OCB/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/OCB/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/OCB/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/OCB/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/OCB/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/OCB/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/OCB/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/OCB/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/OCB/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/OCB/odoo/addons/base/models/res_config.py", line 635, in execute
    to_uninstall_modules.button_immediate_uninstall()
  File "<decorator-gen-64>", line 2, in button_immediate_uninstall
  File "/opt/odoo/OCB/odoo/addons/base/models/ir_module.py", line 73, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/OCB/odoo/addons/base/models/ir_module.py", line 578, in button_immediate_uninstall
    return self._button_immediate_function(type(self).button_uninstall)
  File "/opt/odoo/OCB/odoo/addons/base/models/ir_module.py", line 553, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/OCB/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/OCB/odoo/modules/loading.py", line 473, in load_modules
    getattr(py_module, uninstall_hook)(cr, registry)
  File "<string>", line 61, in _uninstall_rebrand_system
  File "/usr/lib/python3.5/ast.py", line 84, in literal_eval
    return _convert(node_or_string)
  File "/usr/lib/python3.5/ast.py", line 57, in _convert
    return list(map(_convert, node.elts))
  File "/usr/lib/python3.5/ast.py", line 55, in _convert
    return tuple(map(_convert, node.elts))
  File "/usr/lib/python3.5/ast.py", line 83, in _convert
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: <_ast.Call object at 0x7f87f3a954a8>
```

**Comment by keshrath** [comment]
I'm afraid I can't reproduce it. At least an install on a fresh DB and uninstall worked without any problems.
